Add Pagination
christophrumpel/larastreamers pull request #61
Opened 2021-07-08 21:09 UTC by spaantje

Hi Christoph, 

I saw on the stream that you wanted to add pagination so i took a crack at it with this pull requests. 

I though the best way to do it is by retrieving the Steams in the livewire component instead of the Controllers. (Because that way livewire can paginate). 

Take a look at the changes if you like. Don't know if i did it the way you would like to structure things. 

Some things to consider: 
- Styling on the pagination links needs some work. 
- When clicking a pagination link it's doesn't scroll back to the top. 
- Maybe use a different qty per page.
- I marked one test as skipped because i removed the method from PrepareStreams (it was no longer used). So maybe another test needs to be written in place?

2021-07-09 07:04 UTC, christophrumpel commented
Thanks a lot @spaantje. Will give it a look later today 👍

2021-07-11 16:12 UTC, christophrumpel requested changes
Thanks a lot. I like this approach and it also for adding searches to the stream lists. I just added a few little request changes.

2021-07-11 16:12 UTC, christophrumpel commented on app/Actions/PrepareStreams.php
>  class PrepareStreams
Since this action is now only used to sort the stream, let's rename it to `SortStreamsByDateAction`.

2021-07-11 16:12 UTC, christophrumpel commented on tests/Feature/PrepareStreamsTest.php
>      {
Thanks, I think we can remove this test now. We already check the ordering in the tests for the home or archive page. Please remove it.

2021-07-11 16:44 UTC, spaantje commented
@christophrumpel Both are changed.

2021-07-12 07:23 UTC, merged